services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: db_crud_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
